# Generated by Django 4.2.6 on 2023-10-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('symbol_native', models.CharField(blank=True, max_length=20, null=True)),
                ('name_plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('buys_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('exchage_rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping', to='currency_exchange.currency')),
                ('sell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seles', to='currency_exchange.currency')),
            ],
        ),
    ]
