# Generated by Django 4.2.6 on 2023-10-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='buys_quantity',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='sell_quantity',
        ),
    ]
