# Generated by Django 4.2.6 on 2023-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0002_remove_exchange_buys_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchage_rate',
            field=models.DecimalField(decimal_places=14, max_digits=19),
        ),
    ]
