# Generated by Django 4.2.6 on 2023-10-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0003_alter_exchange_exchage_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='exchage_rate',
            new_name='exchange_rate',
        ),
    ]
